apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nfd-proxmox-host
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: nfd-proxmox-host
  template:
    metadata:
      labels:
        name: nfd-proxmox-host
    spec:
      containers:
        - name: proxmox-host-sidecar
          image: ghcr.io/onedr0p/kubanetics@sha256:ee207e744afe4b398c5a53542ce4905b8b1a1a3003f9549d25e2bbbc58a9f8d8
          command: ["/bin/sh", "-c"]
          args:
            - chmod +x /etc/custom-scripts/proxmox-host.sh && while true; do
                /etc/custom-scripts/proxmox-host.sh;
                sleep 300;
              done
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: custom-scripts
              mountPath: /etc/custom-scripts
              readOnly: false
            - name: features-d
              mountPath: /etc/kubernetes/node-feature-discovery/features.d
              readOnly: false
      volumes:
        - name: custom-scripts
          configMap:
            name: nfd-proxmox-host-script
        - name: features-d
          hostPath:
            path: /etc/kubernetes/node-feature-discovery/features.d
            type: DirectoryOrCreate
