---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellyseerr
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: jellyseerr-secret
    template:
      engineVersion: v2
      data:
        JELLYSEERR__AUTH__APIKEY: "{{ .JELLYSEERR_API_KEY }}"
        DB_HOST: &dbHost postgres16-rw.database-system.svc.cluster.local
        DB_PORT: "5432"
        DB_USER: &dbUser "{{ .JELLYSEERR_POSTGRES_USER }}"
        DB_PASS: &dbPass "{{ .JELLYSEERR_POSTGRES_PASSWORD }}"
        DB_NAME: &dbName jellyseerr_main
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: jellyseerr
    - extract:
        key: cloudnative-pg
