apiVersion: moco.cybozu.com/v1beta2
kind: BackupPolicy
metadata:
  namespace: database-system
  name: daily
spec:
  # Backup schedule.  Any CRON format is allowed.
  schedule: "@daily"

  jobConfig:
    serviceAccountName: default

    bucketConfig:
      bucketName: "moco"
      endpointURL: https://minio.lan.${SECRET_DOMAIN}:9002
      usePathStyle: true
    envFrom:
    - secretRef:
        name: moco-cluster-secret

    workVolume:
      # Using emptyDir as a working directory is NOT recommended.
      # The recommended way is to use generic ephemeral volume with a provisioner
      # that can provide enough capacity.
      # https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/#generic-ephemeral-volumes
      persistentVolumeClaim:
        claimName: moco-daily-backup
