---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: mysql
        group: infrastructure
        url: tcp://moco-cluster-v0.database-system.svc.cluster.local:3306
        interval: 1m
        ui:
          hide-url: true
          hide-hostname: true
        conditions:
          - "[CONNECTED] == true"
        alerts:
          - type: pushover
