---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ../../../../../shared/templates/volsync
configMapGenerator:
  - name: kometa-configmap
    files:
      - ./configs/config.yml
  - name: kometa-token-updater
    files:
      - ./configs/update-auth-tokens.py
generatorOptions:
  disableNameSuffixHash: true
