apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:dSBVI3iqJ0TXvwN/MMxhijACX6QPqC8qwbJbQvNzzcQ=,iv:QFya1OQq+oRpmHNTY427qMmpWg/6h2DlHGGLN080tiA=,tag:usMVAQXnsc9pq7YVCbBPHA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h4wn0hdn7p9an0uxxg79en2znceln23s60r2d6es4evj9uv2r56qrlkdu5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bTJzRGh4NUVtQk43M2xh
            YjV5RVdDR3FQSCszL28yNVNTSkdZWmU0N1VFCmc3WENUNUorSDdOU1BNTmN6WEpB
            Z25CeU5TVzlHYTdwTjJ2OVJiNE4rWDQKLS0tIFA4VEd3YWJLZnpGUHhUcURQZ0FQ
            aG5CM1lOZ0Z0MHFzTWc1TG5kRytFU1UK4SHhUnn9lU6Va4+cF7HyjJnITS2NNp44
            3gPeRNDHrUJnOfUk7Au92xyRNZVJayin41IJR1HAeoM6fFao4c3lhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-04T02:27:52Z"
    mac: ENC[AES256_GCM,data:viHPKalE4MHncTygZO7V1qlZoaITgZDEGk24puHb88vhHdZ8uKIY3snovNoFzGstIVvmhHLI9TTNqgDrN8fd2qJOfUIZ+3nudRn/1FErl+khALsFUo3VFw/QY47USCaKmSQsE86tiWuG9yIxUO6Q7dlplAtN6rEwu+KeUtRSds0=,iv:snZSNZ6Vmbb5m/RYAUWzHpZ/h/BEOXwLkInDvTjw+jo=,tag:5FHBeDkafhdbWafdkHpBmg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
