---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app headlamp
spec:
  interval: 30m
  chart:
    spec:
      chart: *app
      version: 0.28.0
      sourceRef:
        kind: HelmRepository
        name: *app
        namespace: flux-system
  driftDetection:
    mode: enabled
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: headlamp
    initContainers:
      - image: ghcr.io/headlamp-k8s/headlamp-plugin-flux:v0.1.0-beta-1
        command:
          - /bin/sh
          - -c
          - mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/
        name: headlamp-plugins
        volumeMounts:
          - mountPath: /build/plugins
            name: headlamp-plugins
    config:
      oidc:
        secret:
          create: true
      pluginsDir: /build/plugins
    podAnnotations:
      reloader.stakater.com/auto: "true"
    volumeMounts:
      - mountPath: /build/plugins
        name: headlamp-plugins
    volumes:
      - name: headlamp-plugins
        persistentVolumeClaim:
          claimName: headlamp
    persistentVolumeClaim:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 1Gi
      storageClassName: "longhorn"
    ingress:
      enabled: true
      ingressClassName: internal
      annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: Headlamp
        gethomepage.dev/pod-selector: "app.kubernetes.io/name=headlamp"
        gethomepage.dev/description: Web UI for managing Kubernetes clusters
        gethomepage.dev/icon: "https://raw.githubusercontent.com/headlamp-k8s/headlamp/main/frontend/public/favicon.ico"
        gethomepage.dev/group: Observability
      hosts:
        - host: &host "headlamp.${SECRET_DOMAIN}"
          paths:
            - path: /
              type: ImplementationSpecific
              service:
                identifier: app
                port: http
      tls:
        - hosts:
            - *host

    extraManifests:
      - |
        apiVersion: v1
        kind: Secret
        type: kubernetes.io/service-account-token
        metadata:
          name: {{ include "headlamp.fullname" . }}-admin-token
          namespace: {{ .Release.Namespace }}
          annotations:
            kubernetes.io/service-account.name: {{ include "headlamp.serviceAccountName" . }}
