---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: 1.9.2
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    metrics:
      serviceMonitor:
        enabled: true
    # Hotfix for 1.90 https://longhorn.io/docs/1.9.0/important-notes/#warning
    preUpgradeChecker:
      upgradeVersionCheck: false # Remove this on next chart update
    image:
      longhorn:
        manager:
          tag: v1.9.0-hotfix-1 # Remove this on next chart update
    defaultSettings:
      defaultReplicaCount: 3
      backupstorePollInterval: 0
      createDefaultDiskLabeledNodes: true
      restoreVolumeRecurringJobs: true
      storageOverProvisioningPercentage: 100
      storageMinimalAvailablePercentage: 1
      guaranteedEngineManagerCPU: 20
      guaranteedReplicaManagerCPU: 20
      orphanAutoDeletion: true
      replicaNodeLevelSoftAntiAffinity: true
      replicaZoneLevelSoftAntiAffinity: true
      defaultDataLocality: best-effort
      replicaAutoBalance: best-effort
      concurrentAutomaticEngineUpgradePerNodeLimit: 3
      defaultLonghornStaticStorageClass: longhorn
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      defaultDataPath: "/var/mnt/longhorn"
    ingress:
      enabled: true
      ingressClassName: internal
      host: longhorn.${SECRET_DOMAIN}
      tls: true
      annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: Kubernetes Storage
        gethomepage.dev/group: Storage
        gethomepage.dev/icon: longhorn
        gethomepage.dev/name: Longhorn
        gethomepage.dev/href: https://longhorn.${SECRET_DOMAIN}/#/dashboard
        gethomepage.dev/app: longhorn
