---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: changedetection
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      changedetection:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/dgtlmoon/changedetection.io
              tag: 0.55.7@sha256:736331d2787f94d3201b64aa641e090f67e28577ba505bd7ba5d7c1841e1e0ca
            env:
              TZ: ${TIMEZONE}
              PORT: &port 5000
              USE_X_SETTINGS: 1
              PLAYWRIGHT_DRIVER_URL: ws://localhost:3000/?stealth=1&--disable-web-security=true&--user-data-dir=~/browserless-cache-123
              # resources:
              #   requests:
              #     cpu: 10m
              #     memory: 100Mi
              #   limits:
              #     memory: 250Mi
          browser:
            image:
              pullPolicy: IfNotPresent
              repository: ghcr.io/browserless/chromium
              tag: v2.52.2@sha256:489361fa81fd8803a6e35f955c1f94007e928f022e84ade3ca90fdab2d6e14e6
            env:
              CONCURRENT: "10"
              DATA_DIR: /profile
              DOWNLOAD_DIR: /downloads
              TIMEOUT: "60000"
              SCREEN_WIDTH: "1920"
              SCREEN_HEIGHT: "1024"
              SCREEN_DEPTH: "16"
              ENABLE_DEBUGGER: "false"
              PREBOOT_CHROME: "true"
              CHROME_REFRESH_TIME: "600000"
              DEFAULT_BLOCK_ADS: "true"
              DEFAULT_STEALTH: "true"
    service:
      app:
        controller: changedetection
        ports:
          http:
            port: *port

    ingress:
      app:
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Web Site Change Detection, Restock monitoring and notifications.
          gethomepage.dev/group: Automation
          gethomepage.dev/icon: changedetection.png
          gethomepage.dev/name: ChangeDetection-io
          gethomepage.dev/widget.type: changedetectionio
          gethomepage.dev/widget.url: http://changedetection.default.svc:5000
          gethomepage.dev/widget.key: "{{ `{{HOMEPAGE_VAR_CHANGEDETECTION_TOKEN}}` }}"
        hosts:
          - host: changedetection.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
    persistence:
      datastore:
        existingClaim: changedetection
