# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app changedetection
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      *app :
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/dgtlmoon/changedetection.io
              tag: "0.50.6"
            env:
              TZ: ${TIMEZONE}
              PORT: &port 5000
              USE_X_SETTINGS: 1
              PLAYWRIGHT_DRIVER_URL: ws://localhost:3000/?stealth=1&--disable-web-security=true&--user-data-dir=~/browserless-cache-123
            # resources:
            #   requests:
            #     cpu: 10m
            #     memory: 100Mi
            #   limits:
            #     memory: 250Mi
          browser:
            image:
              pullPolicy: IfNotPresent
              repository: docker.io/browserless/chrome
              tag: "1-chrome-stable"
            env:
              - name: SCREEN_WIDTH
                value: "1920"
              - name: SCREEN_HEIGHT
                value: "1024"
              - name: SCREEN_DEPTH
                value: "16"
              - name: ENABLE_DEBUGGER
                value: "false"
              - name: PREBOOT_CHROME
                value: "true"
              - name: CONNECTION_TIMEOUT
                value: "300000"
              - name: MAX_CONCURRENT_SESSIONS
                value: "10"
              - name: CHROME_REFRESH_TIME
                value: "600000"
              - name: DEFAULT_BLOCK_ADS
                value: "true"
              - name: DEFAULT_STEALTH
                value: "true"
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port

    ingress:
      app:
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Web Site Change Detection, Restock monitoring and notifications.
          gethomepage.dev/group: Automation
          gethomepage.dev/icon: changedetection.png
          gethomepage.dev/name: ChangeDetection-io
          gethomepage.dev/widget.type: changedetectionio
          gethomepage.dev/widget.url: http://changedetection.default.svc:5000
          gethomepage.dev/widget.key: "{{ `{{HOMEPAGE_VAR_CHANGEDETECTION_TOKEN}}` }}"
        hosts:
          - host: changedetection.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
    persistence:
      datastore:
        existingClaim: *app
