---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gha-runner-scale-set
spec:
  interval: 30m
  chart:
    spec:
      chart: gha-runner-scale-set
      version: 0.10.1
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: gha-runner-scale-set-controller
      namespace: actions-runner-system
  valuesFrom:
    - targetPath: githubConfigSecret.github_token
      kind: Secret
      name: actions-runner-controller-auth-secret
      valuesKey: ACTION_RUNNER_CONTROLLER_GITHUB_TOKEN
  values:
    nameOverride: gha-runner-scale-set
    runnerScaleSetName: gha-runner-scale-set
    githubConfigUrl: https://github.com/cbrherms/home-ops
    minRunners: 1
    maxRunners: 10
    containerMode:
      type: dind
    template:
      spec:
        containers:
          - name: runner
            image: ghcr.io/joryirving/actions-runner:2.321.0@sha256:81f64a94e65c70c676d29e1779d1cc4069665abb970803c76beb08ca234638b6
            command: ["/home/runner/run.sh"]
    controllerServiceAccount:
      name: gha-runner-scale-set-controller
      namespace: actions-runner-system
