---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: spoolman
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: spoolman-secret
    template:
      engineVersion: v2
      data:
        SPOOLMAN_DB_HOST: postgres16-rw.database-system.svc.cluster.local
        SPOOLMAN_DB_NAME: "{{ .SPOOLMAN_DB_NAME }}"
        SPOOLMAN_DB_USERNAME: "{{ .SPOOLMAN_DB_USERNAME }}"
        SPOOLMAN_DB_PASSWORD: "{{ .SPOOLMAN_DB_PASSWORD }}"
        INIT_POSTGRES_DBNAME: "{{ .SPOOLMAN_DB_NAME }}"
        INIT_POSTGRES_HOST: postgres16-rw.database-system.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .SPOOLMAN_DB_USERNAME }}"
        INIT_POSTGRES_PASS: "{{ .SPOOLMAN_DB_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: spoolman
