---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app drl-exporter
spec:
  interval: 30m
  chart:
    spec:
      chart: drl-exporter
      version: 0.1.3
      sourceRef:
        kind: HelmRepository
        name: tektonops
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: *app
    image:
      name: kha7iq/drl-exporter
      repository: ghcr.io
      tag: v2.1.3
      pullPolicy: IfNotPresent
    serviceMonitor:
      enabled: true
      interval: 1m
      scrapeTimeout: 30s
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        memory: 128Mi
