apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:09hWo+1F6AJEZieIes6dOsUeWHCDz7sTS7tymuKhSyLIi0uS,iv:3LfMShKx2v9l8GtmyhYM2WJHOSUEooQAhEItX2r748I=,tag:8ZUnfKjpmgzBHn6qGReIOg==,type:str]
    credentials.json: ENC[AES256_GCM,data:CoC9FP3v4ogUDyIHvz5tT/P5QWz5qtbF7YuzJarz9lg8f/AVZo32NdzxLUBtk5qQ3rimQ3YjGhxWGaoGB9E7VW3hneJuk1Eyu4SaakG9Dy/XCVlXkf0duBHZrX+dPb6sNCRyND3iGpMNzifWfOzHerHo4SOf5cvU+LhNt7R4vcbB+BzaUS6oxISooL1QxQ0tFCqf4BRPjGMHLBvUxIwdOk0SHEw0GnnB7RONqIg0SQ==,iv:7R2E/CUp7Nf/dnCGJ6Hc13Iv0eHJDoTfNWJaSqO4B8k=,tag:flySINoqVLTweauMP/2JTA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h4wn0hdn7p9an0uxxg79en2znceln23s60r2d6es4evj9uv2r56qrlkdu5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UWJwSWhDcWZOTWFObTJL
            THpMMWQ0Rlp0MG53eFNyWnh3VDh1Vk94WEYwCnlMeXdBbFp3dEp5dmlNUHdmKzJT
            WlJ5Q3prRVlYYjNub2NoY0VQYVoybk0KLS0tIGl0WHp5SVZiWFBZRWcrUmtBdllt
            RzBkYzZuSUhTNGwrbWU5T2ZZTTRjZUUKJExjWtiqcLHTQjOUAzTYaYwJfz+vFR1H
            MSoVZqnLnXvhWt2mUF1ZhvVEU5QO4v7qW1+OfgXVVRgyLc4L74X1ZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-04T02:27:52Z"
    mac: ENC[AES256_GCM,data:boi+8W03DbfJFVt4rkXL0OsMcDxaa/YSAuma5a54qE+zE92baGdmnkIBAD6vB6ZwLi7kAvAQmK6+XupR+GWEyPkw462+2W9aumNgzkcUJ+8nuUrtVszp+C5uD6sFE2aEyJ4u98WVsOXFlZJ7IOo7wzz2woi2R2PBwmlgligMI/k=,iv:ErFStWwHE/pgCfZ4hn6WP/wr//zrHIUVkG+9Ksnw2wE=,tag:cGSfv5S9ya01E+m6B8nA4w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
