---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: autobrr
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: autobrr-secret
    template:
      engineVersion: v2
      data:
        AUTOBRR__DATABASE_TYPE: postgres
        AUTOBRR__POSTGRES_DATABASE: &dbName autobrr_main
        AUTOBRR__POSTGRES_HOST: &dbHost postgres16-rw.database-system.svc.cluster.local
        AUTOBRR__POSTGRES_USER: &dbUser "{{ .POSTGRES_USER }}"
        AUTOBRR__POSTGRES_PASS: &dbPass "{{ .POSTGRES_PASS }}"
        AUTOBRR__POSTGRES_PORT: "5432"
        AUTOBRR__SESSION_SECRET: "{{ .SESSION_SECRET }}"
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: autobrr
    - extract:
        key: cloudnative-pg
