---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mam-scripts
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mam-scripts-secret
    template:
      engineVersion: v2
      data:
        MAM_ID_AUTODL: "{{ .MAM_ID_AUTODL }}"
        MAM_ID_AUTOSPEND: "{{ .MAM_ID_AUTOSPEND }}"
        MAM_ID_SEEDBOX: "{{ .MAM_ID_SEEDBOX }}"
  dataFrom:
    - extract:
        key: mam-scripts
