---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./coredns.yaml
  - ./jetstack.yaml
  - ./metrics-server.yaml
  - ./openebs.yaml
  - ./postfinance.yaml
  - ./prometheus-community.yaml
  - ./spegel.yaml
  - ./stakater.yaml
  - ./external-dns.yaml
  - ./ingress-nginx.yaml
  - ./k8s-gateway.yaml
  - ./backube.yaml
  - ./piraeus.yaml
  - ./kubernetes-dashboard.yaml
  - ./grafana.yaml
  - ./external-secrets.yaml
  - ./christianhuth.yaml
  - ./intel.yaml
