---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pve-exporter
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: pve-exporter-secret
    template:
      engineVersion: v2
      data:
        password: "{{ .PVE_PASSWORD }}"
        user: "prometheus@pam"
  dataFrom:
    - extract:
        key: pve-exporter
