---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-pve-exporter
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      prometheus-pve-exporter:
        containers:
          app:
            image:
              repository: prompve/prometheus-pve-exporter
              tag: 3.4.7@sha256:75e8eaf7a1b00494ac60cbc6ee7abaa7b9c46ea6d08f35af985c177300bb2f53
            envFrom:
              - secretRef:
                  name: pve-exporter-secret
            env:
              PVE_VERIFY_SSL: false
              PVE_USER: "prometheus@pve"
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
    service:
      app:
        controller: prometheus-pve-exporter
        ports:
          http:
            port: 9221
