apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:zJx2KM81fB94qAFAkOVijcYsLVHCx1bc9FhqY1+F6W7lPU/ifRwusg==,iv:HROo3PYZuuXQKzGtjF9GfKhInTVT3jp3NuVYCzYjMCg=,tag:IeP/YwCBCSr0L3qRMUyT0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h4wn0hdn7p9an0uxxg79en2znceln23s60r2d6es4evj9uv2r56qrlkdu5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4S2pKR25HckMwQTI2T0hS
            MHpYSko5TVFoZnN1UVlQSmVMUG9VZ3FKNkJBCkljUXg0Y0tzWjNTRlRWc2lKT2ph
            RUVnaDVOeTk1a1VTa2dwang2V0RqelUKLS0tIFN3dG12YThVWk9kRUtoUG1jSW1Q
            VzRwUTFaa0lQZ3p5U2RPQ1psWVEzdVUKHixE5AKooyJS2MnBP/c4lruR389iSCOx
            l2ILADLHBsrtgBUQopAQROMZGtZnYjmRnPWejY+BM0dXXU4H9lMQCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-30T00:40:53Z"
    mac: ENC[AES256_GCM,data:q8DMxAZWmpRE/b2rwP4f5d5TV8kk+jyEmQK3HqrVSfpHu6WHbFKE69KFxwX7v+kikcTMMFrl74HXf+QORp37oO3aa11E+LoYjf0GIxV+kj1yA7H6k24Fku3bS4l814G1xgGF19CPtRrpSk9nG7mfPBT27cr+ImgfK2LOOaqQUBY=,iv:pwPHfG8REy+UjWWMHGseeqrqcVeQs2QwON8yJDwT7gU=,tag:eKTVnxKUawOhzFK5XTwnGg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
