apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:6QNZP2YTSNL5Eo6rmZLKPUQjQiMvEJ6lqZhFbsyrSBOi2XFnIHuizw==,iv:AibA/LUEk0v2uLNSLBTQMorz81NGpXKNe7WAe/IE5rg=,tag:xgyFokrI2d48LRmeS7qksQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h4wn0hdn7p9an0uxxg79en2znceln23s60r2d6es4evj9uv2r56qrlkdu5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkMHVPeXBsZFlFZGRYa21P
            YzIxN2dIR3VPUXlXWDBHZk9ZekxCWDNFclNjCmV0QkI2WUNNSW5jNFcvWjNMcDEy
            dnc5enREVFREemlVc1VuSStWeitNL00KLS0tIFVnTUFqQ1JsNFo5QkVQMC9qdkg0
            QTRYaFZqelE0TUo0Z0NiY1R5WmFPeUkKpMo87XSdsVaMiVRgsnK2vylYl+YxOOfp
            +M5jV3Aoq77JGKxvZTZEOWlN193Cl8tVEeTP5ilYDCCungujyBo3KA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-04T02:27:52Z"
    mac: ENC[AES256_GCM,data:5ZKJoNi4bU5f24hlNkHb/0jwy7PsZUvt469s2xOUlH4ce3xKh0LKHbOKH5CjWs51TT9vPIQ/zPXAIOsGpZAngUM8D6w/UzEid05yE88U4joAhNvsSmJ7OJU2xJOmY56nE415zByipeRT89sDRefPy6CUTz6dLuZ/ABWVtEkhbs0=,iv:kA+aIJkB3S9AerE0e8HEfKgnF8/ZET8eW4e4tbbCZWc=,tag:I3mAbiNpnzfxJSxzQjqmrw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
