---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: &name smartctl-exporter
spec:
  metricsPath: /metrics
  relabelings:
    - action: replace
      replacement: *name
      targetLabel: job
  staticConfigs:
    - targets:
        - "truenas.lan.${SECRET_DOMAIN}:9633"
