apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:j2UPvoXvsQ1DeVxN,iv:gsqlo3DJbyY4Y6y2r3HedecJV9eGvl+HjX8yczxrXY8=,tag:xBV5nRcEKEBHB/XmspvSzg==,type:str]
    SECRET_DOMAIN_ALT: ENC[AES256_GCM,data:f4isZMZUrtZBrxtFU4atpg==,iv:uPE/yKnsIBOQ66ZN8LLYHIZOeEEW/M/OZZcAk7DgbUs=,tag:lWqVVf95TDeVrHqKm8At3Q==,type:str]
    SECRET_DOMAIN_TCS: ENC[AES256_GCM,data:qOdfsEojIzGNSWvRekgBiD8=,iv:yxnckWQ7yBJS5uH20145wqP5YeD7q/t14M8818CrNtE=,tag:jfK8KzruPaW0zF5I1hQkLQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:2LfBjf3FwGGXiJIrUlULnw34C+hW,iv:izEXNgtH2BLILobulKluxYahDzhxK7+FvdJ/19bUuoE=,tag:f9NgAfQ3GZscewsov+g4jw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:tQ615kEx+GpIHAuyVdllsRpf8D6H3EfBlLx5McZChHvTTakY,iv:cEyMJBS2N/HRmgKT4TD/Nvj/pmpTvS4Bo0khgRtgb+o=,tag:fcJ+r81Kn+y+zvC/yJzYUQ==,type:str]
    SECRET_CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:9RzydKfF+x858fGR88hSks6kuYcDjWoy8oAKXEPojgE=,iv:4sKkCLitorNJN+13cZsNAQdcMWm7D8KbWyL8G25EkM4=,tag:qj6xnj3MFB2B2+XSR0Ot6w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h4wn0hdn7p9an0uxxg79en2znceln23s60r2d6es4evj9uv2r56qrlkdu5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMDJOa09KVlJOUFMrd2Ex
            Q2JUVzNEd3VMeXY3RzdFdWdmdE5qRFZ1TnhVCnNxeDc2Z1RlMTBFMXY2aVVtWXhr
            TGt5SHlDL21pZnJ6MXZMTVhhVVFNemMKLS0tIHRGY1kxb0QzUEFrQ1ZDUmJLZTBR
            MFpqcEhKY1R5cHlLUU55TFdRSnFxLzQKFG5pd4GUKkr9fhznkKVWh5vV3xLi1C55
            o+7j9/ea/vRVx9mdFI8/L/qCF9s5p6mYfV0YYObfl5MOdqGn7o1Deg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-04T03:09:35Z"
    mac: ENC[AES256_GCM,data:gZqfaDzMso8oZpGZddGhaUH5A2NBStw0Kalpx09gSVgk/mJyY45dMhCliJPIkMKf/OyJq7aHfHLlzO7cpBTL1kQV+xEzmPYnRjnnm2N2DOgOnZCVlTCeClmI+7bB24u4ZWrjVZI8NPgYCxyBlX2BJBQeZGs+ksbO47odVUFBFWw=,iv:WPRgwJeOcs5u/uz/1+xf0HtHWtyOK82b1BdC4jjPMMc=,tag:oiVxSCsaRbSIC7NxStQ1gQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
