---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lubelogger
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: lubelogger-secret
    template:
      engineVersion: v2
      data:
        # App
        POSTGRES_CONNECTION: "Host=postgres16-rw.database-system.svc.cluster.local:5432;Username={{ .POSTGRES_USER }};Password={{ .POSTGRES_PASS }};Database=lubelogger_main"
        # Mail
        MailConfig__EmailServer: "smtp-relay.network.svc.cluster.local"
        MailConfig__EmailFrom: "lubelogger@noreply.${SECRET_DOMAIN}"
        MailConfig__Port: "25"
        # OIDC
        #OpenIDConfig__Name: authentik
        #OpenIDConfig__ClientId: "{{ .LUBELOGGER_CLIENT_ID }}"
        #OpenIDConfig__ClientSecret: "{{ .LUBELOGGER_CLIENT_SECRET }}"
        #OpenIDConfig__AuthURL: https://sso.${SECRET_DOMAIN}/application/o/authorize/
        #OpenIDConfig__TokenURL: https://sso.${SECRET_DOMAIN}/application/o/token/
        #OpenIDConfig__RedirectURL: https://lubelog.${SECRET_DOMAIN}/Login/RemoteAuth
        #OpenIDConfig__Scope: email
        # Postgres Init
        INIT_POSTGRES_DBNAME: "lubelogger_main"
        INIT_POSTGRES_HOST: "postgres16-rw.database-system.svc.cluster.local"
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
  - extract:
      key: lubelogger
  - extract:
      key: cloudnative-pg
