---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app lubelogger
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: volsync
      namespace: volsync-system
  values:
    controllers:
      lubelogger:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 17.4.0@sha256:a9f405688344a8a6f718e2c344438342ad21540986aeb5ab5fa781831eb2c597
            envFrom: &envFrom
              - secretRef:
                  name: lubelogger-secret
        containers:
          app:
            image:
              repository: ghcr.io/hargata/lubelogger
              tag: v1.4.7
            env:
              TZ: "${TIMEZONE}"
              LC_ALL: "en_GB"
              LANG: "en_GB"
              LUBELOGGER_ALLOWED_FILE_EXTENSIONS: "*"
              LUBELOGGER_DOMAIN: "lubelogger.${SECRET_DOMAIN}"
            envFrom: *envFrom
            resources:
              requests:
                cpu: 15m
                memory: 80M
              limits:
                memory: 256M
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: *app
        ports:
          http:
            port: 8080
    ingress:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Other
          gethomepage.dev/name: Lubelogger
          gethomepage.dev/icon: https://demo.lubelogger.com/defaults/lubelogger_icon_72.png
          gethomepage.dev/description: Vehicle Service Tracking
          gethomepage.dev/widget.type: lubelogger
          gethomepage.dev/widget.url: http://lubelogger.default.svc.cluster.local:8080
          # gethomepage.dev/widget.username: "{{ `{{HOMEPAGE_VAR_LUBELOGGER_USERNAME}}` }}"
          # gethomepage.dev/widget.password: "{{ `{{HOMEPAGE_VAR_LUBELOGGER_PASSWORD}}` }}"
          external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
        className: internal
        hosts:
          - host: &host "lubelogger.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        existingClaim: *app
        globalMounts:
          - path: /App/config
            subPath: config
          - path: /App/data
            subPath: data
          - path: /App/wwwroot/translations
            subPath: translations
          - path: /App/wwwroot/documents
            subPath: documents
          - path: /App/wwwroot/images
            subPath: images
          - path: /App/log
            subPath: log
          - path: /root/.aspnet/DataProtection-Keys
            subPath: keys
      tmp:
        type: emptyDir
        globalMounts:
          - path: /App/wwwroot/temp
