---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./prometheus-operator-crds/ks.yaml
  - ./grafana/ks.yaml
  - ./gatus/ks.yaml
  - ./kromgo/ks.yaml
  - ./kubernetes-dashboard/ks.yaml
  - ./loki/ks.yaml
  - ./promtail/ks.yaml
  - ./blackbox-exporter/ks.yaml
  - ./pve-exporter/ks.yaml
  - ./drl-exporter/ks.yaml
