---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app poenskelisten
  namespace: flux-system
spec:
  targetNamespace: default
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: moco-cluster
    - name: volsync
  path: ./kubernetes/main/apps/default/poenskelisten/app
  prune: false # revert to true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  timeout: 10m
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 10Gi
      GATUS_SUBDOMAIN: wishlists
      GATUS_PATH: /
