apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nfd-proxmox-host
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: nfd-proxmox-host
  template:
    metadata:
      labels:
        name: nfd-proxmox-host
    spec:
      initContainers:
        - name: copy-script
          image: ghcr.io/onedr0p/kubanetics@sha256:e4a45a5ad0f538554dd8220542f27ec7a9306390f5de68cdebfb02b7a8311fc5
          command: ["sh", "-c", "cp /config/proxmox-host.sh /scripts && chmod +x /scripts/proxmox-host.sh"]
          volumeMounts:
            - name: config-scripts
              mountPath: /config
            - name: scripts-tmp
              mountPath: /scripts
      containers:
        - name: proxmox-host-sidecar
          image: ghcr.io/onedr0p/kubanetics@sha256:e4a45a5ad0f538554dd8220542f27ec7a9306390f5de68cdebfb02b7a8311fc5
          command: ["/bin/sh", "-c"]
          args:
            - while true; do
                /scripts/proxmox-host.sh;
                sleep 300;
              done
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: scripts-tmp
              mountPath: /scripts
            - name: features-d
              mountPath: /etc/kubernetes/node-feature-discovery/features.d
              readOnly: false
      volumes:
        - name: config-scripts
          configMap:
            name: nfd-proxmox-host-script
        - name: scripts-tmp
          emptyDir: {}
        - name: features-d
          hostPath:
            path: /etc/kubernetes/node-feature-discovery/features.d
            type: DirectoryOrCreate
