overlays:
  filler_overlay:
    builder_level: episode
    overlay:
      name: text(Filler)
      horizontal_offset: 0
      horizontal_align: center
      vertical_offset: 0
      vertical_align: top
      font_size: 75
      font: config/fonts/Juventus-Fans-Bold.ttf
      back_width: 1920
      back_height: 125
      back_color: "#262626"
    plex_search:
      all:
        episode_label: Filler

  anime_canon_overlay:
    builder_level: episode
    overlay:
      name: text(Anime Canon)
      horizontal_offset: 0
      horizontal_align: center
      vertical_offset: 0
      vertical_align: top
      font_size: 75
      font: config/fonts/Juventus-Fans-Bold.ttf
      back_width: 1920
      back_height: 125
      back_color: "#262626"
    plex_search:
      all:
        episode_label: AnimeCanon

  manga_canon_overlay:
    builder_level: episode
    overlay:
      name: text(Manga Canon)
      horizontal_offset: 0
      horizontal_align: center
      vertical_offset: 0
      vertical_align: top
      font_size: 75
      font: config/fonts/Juventus-Fans-Bold.ttf
      back_width: 1920
      back_height: 125
      back_color: "#262626"
    plex_search:
      all:
        episode_label: MangaCanon

  mixed_canon_overlay:
    builder_level: episode
    overlay:
      name: text(Mixed Canon/Filler)
      horizontal_offset: 0
      horizontal_align: center
      vertical_offset: 0
      vertical_align: top
      font_size: 75
      font: config/fonts/Juventus-Fans-Bold.ttf
      back_width: 1920
      back_height: 125
      back_color: "#262626"
    plex_search:
      all:
        episode_label: Mixed
