templates:

############################
#        TEMPLATES         #
############################

  Charts:
    sort_title: "!01_<<collection_name>>"
    sync_mode: sync
    collection_order: custom
    collection_mode: hide
    schedule: daily
  Oscars:
    sort_title: "!02_<<collection_name>>"
    sync_mode: sync
    collection_order: release.desc
    collection_mode: hide
#    schedule: yearly(03/01)
    schedule: monthly(14)
  AFI's 100:
    sort_title: "!03_<<collection_name>>"
    sync_mode: sync
    collection_order: custom
    collection_mode: hide
#    schedule: yearly(03/01)
    schedule: monthly(14)
  Best Of - Rotten Tomatoes - Years:
    sort_title: "!04_<<collection_name>>"
    sync_mode: sync
    collection_order: custom
    collection_mode: hide
#    schedule: yearly(03/01)
    schedule: monthly(14)
  Best Of - Rotten Tomatoes - Genres:
    sort_title: "!05_<<collection_name>>"
    sync_mode: sync
    collection_order: custom
    collection_mode: hide
#    schedule: yearly(03/01)
    schedule: monthly(14)
  Custom:
    sort_title: "!06_<<collection_name>>"
    sync_mode: sync
    collection_order: alpha
    collection_mode: hide
    schedule: monthly(14)
  Regular:
    sort_title: "!07_<<collection_name>>"
    sync_mode: sync
    collection_order: release
    collection_mode: hide
    schedule: monthly(14)
  Genres:
    sort_title: "!08_<<collection_name>>"
    sync_mode: sync
    collection_order: alpha
    collection_mode: hide
    schedule: weekly(friday)
  IMDb Genres:
    default:
      type: tv_series,mini_series
      year_min: 1980
      rating_min: 7
      votes_min: 50000
      limit: 100
    imdb_search:
      type: <<type>>
      genre: <<genre>>
      release.after: <<year_min>>-01-01
      rating.gte: <<rating_min>>
      votes.gte: <<votes_min>>
      sort_by: rating.desc
      limit: <<limit>>
    sort_title: "!08_<<collection_name>>"
    sync_mode: sync
    collection_order: custom
    collection_mode: hide
    summary: A collection of <<genre>> shows from <<year_min>> to now, with a minimum rating of <<rating_min>> and at least <<votes_min>> votes from IMDb. Sorted by rating.
    schedule: weekly(friday)
  IMDb Keywords:
    default:
      type: tvSeries,tvMiniSeries
      year_min: 1980
      rating_min: 7
      votes_min: 50000
      limit: 100
    imdb_search:
      type: <<type>>
      release.after: <<year_min>>-01-01
      rating.gte: <<rating_min>>
      votes.gte: <<votes_min>>
      sort_by: rating.desc
      limit: <<limit>>
    sort_title: "!09_<<collection_name>>"
    sync_mode: sync
    collection_order: custom
    collection_mode: hide
    summary: A collection of <<keyword>> shows from <<year_min>> to now, with a minimum rating of <<rating_min>> and at least <<votes_min>> votes from IMDb. Sorted by rating.
    schedule: weekly(friday)
  Streaming Services:
    sort_title: "!10_<<collection_name>>"
    sync_mode: sync
    collection_order: release
    collection_mode: hide
    schedule: daily
  Studios:
    sort_title: "!11_<<collection_name>>"
    sync_mode: sync
    collection_order: release
    collection_mode: hide
    schedule: daily
  Holidays:
    sort_title: "!12_<<collection_name>>"
    sync_mode: sync
    collection_order: alpha
    collection_mode: hide
  Years:
    sort_title: "!13_<<collection_name>>"
    sync_mode: sync
    collection_order: release
    collection_mode: hide
    schedule: weekly(friday)
  Audio:
    sort_title: "!14_<<collection_name>>"
    sync_mode: sync
    collection_order: alpha
    collection_mode: hide
    schedule: daily
  Random:
    sort_title: "!15_<<collection_name>>"
    collection_level: episode
    smart_filter:
      all:
        title.is: <<show>>
      sort_by: random
      limit: 1
    collection_mode: hide
    summary: Random <<show>> episode every time it loads.
    schedule: never                                                     # Not scheduled to run because it only needs to run once
  Actors:
    actor: tmdb
    tmdb_person: <<person>>
    sort_title: "!16_<<collection_name>>"
    sync_mode: sync
    collection_order: release
    collection_mode: hide
    schedule: weekly(friday)
  Directors:
    director: tmdb
    tmdb_person: <<person>>
    sort_title: "!17_<<collection_name>>"
    sync_mode: sync
    collection_order: release
    collection_mode: hide
    schedule: weekly(friday)
  Dolby:
    sort_title: "!18_<<collection_name>>"
    sync_mode: sync
    collection_order: custom
    collection_mode: hide
    schedule: weekly(friday)

############################
#       COLLECTIONS        #
############################

collections:

############################
#          CHARTS          #
############################


############################
#         BEST OF          #
############################

############################
#          CUSTOM          #
############################


############################
#         REGULAR          #
############################


############################
#          GENRES          #
############################

############################
#       IMDB GENRES        #
############################


############################
#      IMDB KEYWORDS       #
############################


############################
#    STREAMING SERVICES    #
############################


############################
#         STUDIOS          #
############################


############################
#         HOLIDAYS         #
############################

############################
#          YEARS           #
############################


############################
#          AUDIO           #
############################

############################
#          ACTORS          #
############################

############################
#        DIRECTORS         #
############################

############################
#          DOLBY           #
############################

