apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:HZ78216bRxixx7OV,iv:tEz4Yopzy1l/rAZ/YTLVb8dqA1GHd+Ud0BElHrDQ5+U=,tag:T1EFskL3KV3Ec4ZZp77LMg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:tAGhlMDfln9FyRvvMWA1H0fSHC5l,iv:4+S2Dd8ERqx8f+z1f6MpqAY+WYW4qDZWjF7E2Ia5Qt8=,tag:vLY8TUW2+HcH5f3HcdaRgA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:QzcozxZ7L0l/5R1Q3lgleRrKm0BVSFflWFP2oiAfieGZ43Vl,iv:UXpbvPcWuM2ET/irpJsNt/NawWL09eCopo0XccZFQIM=,tag:szx065uMlpvvX46K4iAZZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h4wn0hdn7p9an0uxxg79en2znceln23s60r2d6es4evj9uv2r56qrlkdu5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYOWhTQ1MrVks3MDNubjdn
            TEJCNEFRUHd1Mlo5QUVSQ211WVVvZDAzVUFBClY4ZThvM3Rsc0dpbUVwNUtWNG5U
            QjU4ajJTdElIRkZndVZ4SjNKOW9vQ28KLS0tIG1LdWo3a0g2N2xRN0ViUTNDa0NG
            Y0xFS3BWb2NHbEVBb3V2VkMxaktlTkkK+QtPXn2w2zq5H7DbpYWiEYf8sHYjWzqO
            oj++1xFVzmKuPNpzKkLd4+WI5xEhTeqN9W1gCB23oN8YEO/q6IVoAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-31T23:51:53Z"
    mac: ENC[AES256_GCM,data:W5bI08393G4duKwyyz87ZCV/2iRZFYuia+jsHsuABwGdTxI5wloUktEXy3TNZEqxYEv3xnWOqg7shi2Q9sLO/rh0snNOvEE5aK3QhWHLoAEAVUhJ80Zq6+Q70bfXYy+jbwAgoY6kYRpE4ZXIW6+jDEy0lS+g5zRGeu2vYUfWtcA=,iv:QfzxTIdrzs6LGECmtbl8qtr2xIr34yX2nMqen6PUJag=,tag:Eh6WIpg3kwhC9Wsl0d87rA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
