apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:1VZSSGrPGSJJvoGmZFCMy837y3aWfySn8+fZwjoSeIE=,iv:GdQ44ZCpRZsY5884aeK9oCvul/riTBJ/VhTwFehLp8M=,tag:jk5CPMzNdmeMIyy+/AA3ag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h4wn0hdn7p9an0uxxg79en2znceln23s60r2d6es4evj9uv2r56qrlkdu5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESHBRUFl1cnhkNGpTNmlN
            c0czaGkwSTVqRXB6b25JNVREVjA0SHg4UFRNCnRyMmw1V3RNdjFHRCtMZnNmMTZx
            Z3FNWjBQL2MvSlh1ZGthZmpmWlRNN2MKLS0tIGo0VXhDTk5zQmNQaGlLeUNzNGsv
            ai95dTVkTG9UVDZ1d2tqTkF3bHcyK1EKBh9YYyHQZaXtErRkPSodFQPibhTXdyIa
            TrIfGtDCKngGJnpiBuxj7xCo6qPUWuS3uhPEx0p2+HZuAbE+K+qA7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-31T23:51:53Z"
    mac: ENC[AES256_GCM,data:K/4RCQDwS+z9N61mHCmcBX+EJjTPMp+n3KTpIRVoCnimPh+Tvn7iVeYq4tw2efGI1vJ6oBpUuPkIRYXUOXhAxiSsOpdExP5X90L96/vlgIWCDDvh80G06KvjrbnDf7cLiOEHoZL2Rnkp4dzNRU5Z14uNXYX1RhgQS03cn0plQhc=,iv:pXTXImTUokbK4Fudk9yexCzDeP8mdU6NjicS1ijkf0M=,tag:E+5nT8b3ACTzpMisWEiNrw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
