---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  labels:
    app.kubernetes.io/name: homepage
data:
  bookmarks.yaml: |
    - Git:
        - kubesearch:
            - icon: kubernetes-dashboard.png
              href: https://kubesearch.dev
        - flux-cluster-template:
            - icon: github.png
              href: https://github.com/onedr0p/flux-cluster-template
        - GitHub Repo (home-ops):
            - icon: github.png
              href: https://github.com/cbrherms/home-ops
  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
  services.yaml: |
    - Network:
        - Cloudflared:
            href: https://dash.cloudflare.com
            icon: cloudflare-zero-trust.png
            description: Cloudflared Tunnel
            widget:
              type: cloudflared
              accountid: "{{HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID}}"
              tunnelid: "{{HOMEPAGE_VAR_CLOUDFLARED_TUNNELID}}"
              key: "{{HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN}}"
    - Automation:
        - Home Assistant:
            href: http://192.168.0.43:8123
            icon: home-assistant.svg
            widget:
              type: homeassistant
              url: http://192.168.0.43:8123
              key: "{{HOMEPAGE_VAR_HA_TOKEN}}"
    - Infrastructure:
        - Unraid:
            icon: unraid.png
            description: Media NAS
            href: http://unraid.lan.${SECRET_DOMAIN}
            widget:
              type: customapi
              url: http://unraid.lan.${SECRET_DOMAIN}:24940
              method: GET # this doesn't matter
              mappings:
                - field:
                    array_total: free
                  label: array free
                  format: number
                  suffix: GiB
                - field:
                    array_total: free_percent
                  label: percent
                  format: percent
                - field:
                    network_total: rx_MiBs
                  label: rx
                  format: float
                  suffix: MiB/s
                - field:
                    network_total: tx_MiBs
                  label: tx
                  format: float
                  suffix: MiB/s
        - TrueNAS:
            href: https://192.168.0.12
            icon: truenas.png
            description: Backup NAS
            widget:
              type: truenas
              url: https://192.168.0.12
              key: "{{HOMEPAGE_VAR_TRUENAS_API_KEY}}"
        - pfSense:
            href: https://192.168.0.1
            icon: pfsense.png
            description: pfSense
            siteMonitor: https://192.168.0.1
            widget:
                type: pfsense
                url: https://192.168.0.1
                username: {{HOMEPAGE_VAR_PFSENSE_USERNAME}}
                password: {{HOMEPAGE_VAR_PFSENSE_PASSWORD}}
                wan: igb0
                version: 2
  settings.yaml: |
    title: Dashboard
    theme: dark
    color: slate
    headerStyle: clean
    layout:
      Home:
        style: column
        icon: mdi-home-analytics
      Media Management:
        style: row
        columns: 4
        icon: mdi-movie-cog
      Infrastructure:
        style: row
        columns: 4
        icon: mdi-server
      Git:
        style: column
        icon: mdi-github
      Automation:
        style: column
        icon: mdi-home-automation
      Network:
        style: column
        icon: mdi-vpn
      Observability:
        style: row
        columns: 4
        icon: mdi-chart-line
  widgets.yaml: |
    - resources:
        backend: kubernetes
        cpu: true
        expanded: true
        memory: true
    - kubernetes:
        cluster:
          cpu: true
          memory: true
          show: true
          showLabel: true
          label: cluster
        nodes:
          cpu: true
          memory: true
          show: false
          showLabel: true
    - search:
        provider: [google, duckduckgo]
        focus: false
        target: _blank
    - greeting:
        text_size: xl
        text: "Welcome!"
    - datetime:
        text_size: l
        format:
          dateStyle: long
          timeStyle: short
          hourCycle: h23
