---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: homepage-secret
    template:
      engineVersion: v2
      data:
        HOMEPAGE_VAR_OVERSEERR_TOKEN: "{{ .OVERSEERR_API_KEY }}"
        HOMEPAGE_VAR_SONARR_TOKEN: "{{ .SONARR_API_KEY }}"
        HOMEPAGE_VAR_RADARR_TOKEN: "{{ .RADARR_API_KEY }}"
        HOMEPAGE_VAR_PROWLARR_TOKEN: "{{ .PROWLARR_API_KEY }}"
        HOMEPAGE_VAR_BAZARR_TOKEN: "{{ .BAZARR_API_KEY }}"
        HOMEPAGE_VAR_JELLYSEERR_TOKEN: "{{ .JELLYSEERR_API_KEY }}"
        HOMEPAGE_VAR_AUTHENTIK_TOKEN: "{{ .AUTHENTIK_TOKEN }}"
        HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID: "{{ .CLOUDFLARE_ACCOUNT_TAG }}"
        HOMEPAGE_VAR_CLOUDFLARED_TUNNELID: "{{ .CLOUDFLARE_TUNNEL_ID }}"
        HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN: "{{ .CLOUDFLARE_API_KEY }}"
        HOMEPAGE_VAR_GRAFANA_USERNAME: "{{ .GRAFANA_ADMIN_USERNAME }}"
        HOMEPAGE_VAR_GRAFANA_PASSWORD: "{{ .GRAFANA_ADMIN_PASSWORD }}"
        HOMEPAGE_VAR_HA_TOKEN: "{{ .TALOS_CLUSTER_HA_TOKEN }}"
        HOMEPAGE_VAR_TRUENAS_API_KEY: "{{ .TRUENAS_API_KEY }}"
        HOMEPAGE_VAR_PFSENSE_USERNAME: "{{ .pfsense_username }}"
        HOMEPAGE_VAR_PFSENSE_PASSWORD: "{{ .pfsense_password }}"
  dataFrom:
    - extract:
        key: authentik
    - extract:
        key: overseerr
    - extract:
        key: sonarr
    - extract:
        key: radarr
    - extract:
        key: prowlarr
    - extract:
        key: bazarr
    - extract:
        key: jellyseerr
    - extract:
        key: cloudflare
    - extract:
        key: grafana
    - extract:
        key: homeassistant
    - extract:
        key: truenas
    - extract:
        key: pfsense
      rewrite:
        - regexp:
            source: "(.*)"
            target: "pfsense_$1"
