apiVersion: v1
kind: Secret
metadata:
    name: homepage-secret
stringData:
    HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID: ENC[AES256_GCM,data:V6ub5lYQLS7e6xi8K6Zi6S89KXIhu6iVFMI9r3m3cpE=,iv:xZuTHVQCiiymjPU88ULO2i8+mlL5ayukChFAnpxwJ4E=,tag:OhMqm8xtsbxELXkBl2k52A==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_TUNNELID: ENC[AES256_GCM,data:270s1rSywEMS/rFbaXMcNzssYCfULh0SfxTb27P5sj+Ztijn,iv:LFMePkcxECYvoQ0c63AjfMU8WGIHWmBVmCxMwnSxVNk=,tag:3ypsFlyGefZ+cpyer5LvbA==,type:str]
    HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN: ENC[AES256_GCM,data:OzOkjT+uk2zUaVbFVfzFwqLbeEOJQnAR0vuv6qgKIBmoT4B7xyJPhg==,iv:OL6lpwMYOmCQi6l6FuE/nz1nMHq9lNKZ4Oe8uZpr0Sg=,tag:ewg019LxPwRw3PmpAMAlwA==,type:str]
    HOMEPAGE_VAR_GRAFANA_USERNAME: ENC[AES256_GCM,data:2dJigQA=,iv:cqqBDspnC6o9G0+XLRczlUAGacnkulleCbNmBeSaHiQ=,tag:arj3i1zncqeo7pzWD9DVWw==,type:str]
    HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:4mpYztz56D4I40u4rqSUsNZyz+YRLe01G7qocQ==,iv:eST8t+cztoEppk+MubPnz1u+hUuTnJigwJhWOqjql0w=,tag:u+unCOWvkbVXkAsuyaAOWA==,type:str]
    HOMEPAGE_VAR_HA_TOKEN: ENC[AES256_GCM,data:90DQmhsFq2jG0BDDvUs4mEwLDJrVZXt455ww9WyKj8B9EOt5/aVo/IbF4CdmLoWQLyS9jicRmxC7FHfrENbcKs081QMNl6tJRHpo4MzSw6cs3xj/Luicl46LLv794N0K0ujNg1x0iLgtJzA6qU+4TR/9GDCafMUhYaz15EEScjD+0R4Ma6WU8DxDwW0O7GtYBC6PT5gIu7OGXhKOXcxo80t2TSbpCxrZ4maO5V4InUeytZeKeeiC,iv:XMTqVW6WQcS+KneUadw5AJd38hPTIH/ARiXBhXkZ6sc=,tag:dkuBZqKMHB0B4j4BNg5YjA==,type:str]
    HOMEPAGE_VAR_TRUENAS_API_KEY: ENC[AES256_GCM,data:VzBSUeBvXN3EmJSM6HvxlEfiOxACVaH0W+oJn65vy2ZiDiNlds0i1iUkEkvlYCZ4bZHAUuvHrCkeo1CIDuw08R6l,iv:Ki6P3AlGotpFwIBF/G00nh/PLjjBLZVhwr72InWgaE8=,tag:Fuv/VPyYzV8YnwzRubM2Gw==,type:str]
    HOMEPAGE_VAR_PFSENSE_USERNAME: ENC[AES256_GCM,data:5Mz1lIw=,iv:+XNda7dHgdsznugfajAd6uwkHYZqr+cGWp7w4deu3xk=,tag:89irb8F1XhQ7XuvDXG6miA==,type:str]
    HOMEPAGE_VAR_PFSENSE_PASSWORD: ENC[AES256_GCM,data:f5kFtKaKSjsLtHC+DHk=,iv:Aqkt4XUGcl8WWSKL50V4H4rHUwqXA2FSPMeXDbn5WlY=,tag:gsir816qezzxJfSShW/tQA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h4wn0hdn7p9an0uxxg79en2znceln23s60r2d6es4evj9uv2r56qrlkdu5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdkJwTEZxK1BQeG95V0lR
            NmVnbWVQSnBRK1JVV2lrZ2lCSTErUlZ0U2tnCnZwUWpEMVYvQ3gzMHJGZjA0ZTdl
            b25wTm90NmpwN1liUUFlTndQUGxQbjAKLS0tIE16OFN3Q3JHaGV1Mlk3M0RkdXRG
            dXgxN0pzRXVpOU5LVnFDLytMVlVsbG8K7MXnWyPnjdA3BI7hwuL51wZxTJuzfTHR
            vbP+hky0n94pt3mIG5a6N/wO3NsybWd8S5JPc0GCg6SY18jyyuvwkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-09T01:37:54Z"
    mac: ENC[AES256_GCM,data:h0mZ2v8txjANL3hI69wpvJ5Z7UVGL+SE97hN0K4B0g41FhzHsOFPVJuY/KObaiDSVDfUtuy2NnbODWtVqt3clCfkODQl14TPaHBvybLdoz2HPj/CFM4DVTCaTvofxq3ks3vL2HKyfe/mRUT/oqf8/OuZhUNqNKv0isK3ztLdAd0=,iv:JfWIjyS0m2oLKbYaU2yAOPlVJAmaPTeIbJqRLLZEcpQ=,tag:ptS6QumYzaUgRIPGNHUeCw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
