---
version: "3"

tasks:

  test:
    desc: Test OnePassword
    cmds:
      - op item get kubernetes --fields label=KUBECONFIG_MAIN | tr -d '"'
      - kubectl config view --flatten
    preconditions:
      - which op
      - sh: 'op whoami'
        msg: "Are you signed in? If not try 'eval $(op signin)'"

  push:
    desc: Push all kubeconfig to OnePassword
    cmds:
      - op item edit kubernetes KUBECONFIG[text]="$(kubectl config view --flatten)" &>/dev/null
      - op item edit kubernetes KUBECONFIG_BASE64[text]="$(kubectl config view --flatten | base64 -w 0)" &>/dev/null
      - task: push-main
#      - task: push-utility
    preconditions:
      - which op
      - sh: 'op whoami'
        msg: "Are you signed in? If not try 'eval $(op signin)'"

  push-main:
    desc: Push main kubeconfig/talosconfig to OnePassword
    cmds:
      - op item edit kubernetes KUBECONFIG_MAIN[text]="$(cat {{.ROOT_DIR}}/kubernetes/main/kubeconfig)" &>/dev/null
      - op item edit kubernetes TALOSCONFIG_MAIN[text]="$(cat {{.ROOT_DIR}}/kubernetes/main/bootstrap/talos/clusterconfig/talosconfig)" &>/dev/null
      - op item edit kubernetes TALOSCONFIG_MAIN_BASE64[text]="$(cat {{.ROOT_DIR}}/kubernetes/main/bootstrap/talos/clusterconfig/talosconfig | base64 -w 0)" &>/dev/null
    preconditions:
      - which op

  push-utility:
    desc: Push Utility kubeconfig to OnePassword
    cmds:
      - op item edit kubernetes KUBECONFIG_UTILITY[text]="$(cat {{.ROOT_DIR}}/kubernetes/utility/bootstrap/kubeconfig)" &>/dev/null
      - op item edit kubernetes TALOSCONFIG_UTILITY[text]="$(cat {{.ROOT_DIR}}/kubernetes/utility/bootstrap/talos/clusterconfig/talosconfig)" &>/dev/null
      - op item edit kubernetes TALOSCONFIG_UTILITY_BASE64[text]="$(cat {{.ROOT_DIR}}/kubernetes/utility/bootstrap/talos/clusterconfig/talosconfig | base64 -w 0)" &>/dev/null
    preconditions:
      - which op

  pull:
    desc: Pull Kubeconfig from OnePassword
    cmds:
      - mkdir -p ~/.kube
      - mkdir -p ~/.talos
      - mkdir -p ~/.talos
      - op item get kubernetes --fields label=KUBECONFIG_MAIN | tr -d '"' > {{.ROOT_DIR}}/kubernetes/main/kubeconfig # Main kubeconfig
      - op item get kubernetes --fields label=TALOSCONFIG_MAIN | tr -d '"' > {{.ROOT_DIR}}/kubernetes/main/bootstrap/talos/clusterconfig/talosconfig # Main talosconfig
      - op item get kubernetes --fields label=KUBECONFIG_UTILITY | tr -d '"' > {{.ROOT_DIR}}/kubernetes/utility/kubeconfig # Utility kubeconfig
      - op item get kubernetes --fields label=TALOSCONFIG_UTILITY | tr -d '"' > {{.ROOT_DIR}}/kubernetes/utility/bootstrap/talos/clusterconfig/talosconfig # Utility talosconfig
      - op item get kubernetes --fields label=KUBECONFIG | tr -d '"' > ~/.kube/config # Flat kubeconfig
      ## Note: The last `talosconfig` merged becomes the default context
      ## We pull the second talosconfig, and merge the main into it, so main is default
      - op item get kubernetes --fields label=TALOSCONFIG_UTILITY | tr -d '"' > ~/.talos/config # Utility talosconfig
      - talosctl config merge {{.ROOT_DIR}}/kubernetes/main/bootstrap/talos/clusterconfig/talosconfig --talosconfig  ~/.talos/config #Merge main into flat talosconfig
    preconditions:
      - which op
