---
version: "3"

tasks:

  push:
    desc: Push all kubeconfig to OnePassword
    cmds:
      - op item edit kubernetes "KUBECONFIG[text]=$(kubectl config view --flatten)" &>/dev/null
      - op item edit kubernetes "KUBECONFIG_BASE64[text]=$(kubectl config view --flatten | base64 -w 0)" &>/dev/null
      - op item edit kubernetes "TALOSCONFIG[text]=$(cat {{.ROOT_DIR}}/kubernetes/main/bootstrap/talos/talconfig.yaml)" &>/dev/null
    preconditions:
      - which op
