---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./externalsecret.yaml
configMapGenerator:
  - name: plex-filler-tagger-configmap
    files:
      - ./configs/config.yaml
generatorOptions:
  disableNameSuffixHash: true

