---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:3ml8M9H6+X54UYwn,iv:GF0FXQGTUeSVQP09qiK7KhDamKt4lW16EOSCNgfFaxk=,tag:7MgKERbiQ/semuVYp8JxJQ==,type:str]
  SECRET_DOMAIN_ALT: ENC[AES256_GCM,data:7Iz5dGbjfKkCOCF5C0AYLw==,iv:87KelJN7y7tUxA5mEgZGsrAiXRIGCQmjpHr+hcmcROU=,tag:dNm0jsT5zZ4Jkw8rJiKiww==,type:str]
  SECRET_DOMAIN_TCS: ENC[AES256_GCM,data:8f7QIPne/voro/ie/4hnGJ0=,iv:VcSrrNR801+LSL4KZxRtamiB4/7vRsOciDm6azncHX4=,tag:cD6EB/dv5SOgTYpo8P2t2A==,type:str]
  SECRET_ACME_EMAIL: ENC[AES256_GCM,data:eucp9tpKftAvxv52Ow2KoBk9wRyE,iv:JEHKya5iePTmEdoAQ6jF9pqngvSmhA7pLPIma4BU0ag=,tag:1aCsQAr3RNYkxuuhOijPRw==,type:str]
  CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:66P5SfVsg6Nz1qnnmnJNceUoA2ifZW5h8WFdms2jSxQ=,iv:OXbxJ7Jo3lSfR8N7wSYcN8Ct3af51gQjrZZKfkH2kAE=,tag:pXN84xzjk9BZ5P6HB0uRQQ==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:tQ615kEx+GpIHAuyVdllsRpf8D6H3EfBlLx5McZChHvTTakY,iv:cEyMJBS2N/HRmgKT4TD/Nvj/pmpTvS4Bo0khgRtgb+o=,tag:fcJ+r81Kn+y+zvC/yJzYUQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMDJOa09KVlJOUFMrd2Ex
        Q2JUVzNEd3VMeXY3RzdFdWdmdE5qRFZ1TnhVCnNxeDc2Z1RlMTBFMXY2aVVtWXhr
        TGt5SHlDL21pZnJ6MXZMTVhhVVFNemMKLS0tIHRGY1kxb0QzUEFrQ1ZDUmJLZTBR
        MFpqcEhKY1R5cHlLUU55TFdRSnFxLzQKFG5pd4GUKkr9fhznkKVWh5vV3xLi1C55
        o+7j9/ea/vRVx9mdFI8/L/qCF9s5p6mYfV0YYObfl5MOdqGn7o1Deg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1h4wn0hdn7p9an0uxxg79en2znceln23s60r2d6es4evj9uv2r56qrlkdu5
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-01T21:53:39Z"
  mac: ENC[AES256_GCM,data:pCGgWuaFb/3lePXV2ulU4HtckaCexF+Q/Lhkv9jN8n7RRa19jWjRVs567tjc2YtfKQnTj1M0Gd4o5fxG4tTJCAWJEVTB+XNGP3ILDWfjKmWCGwykposFXfag6g18QZqPUlN4LqcTY89+W139YwqpTI/0smTlb1UK/vhvn9QFDLQ=,iv:mvbDSIDAqYDtKLBU83ExDpELcjLRskAEhBtjfpjCdag=,tag:A722oKlBRL530sIy4xRoeQ==,type:str]
  version: 3.13.3
