apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-main
    namespace: flux-system
stringData:
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:tQ615kEx+GpIHAuyVdllsRpf8D6H3EfBlLx5McZChHvTTakY,iv:cEyMJBS2N/HRmgKT4TD/Nvj/pmpTvS4Bo0khgRtgb+o=,tag:fcJ+r81Kn+y+zvC/yJzYUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h4wn0hdn7p9an0uxxg79en2znceln23s60r2d6es4evj9uv2r56qrlkdu5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMDJOa09KVlJOUFMrd2Ex
            Q2JUVzNEd3VMeXY3RzdFdWdmdE5qRFZ1TnhVCnNxeDc2Z1RlMTBFMXY2aVVtWXhr
            TGt5SHlDL21pZnJ6MXZMTVhhVVFNemMKLS0tIHRGY1kxb0QzUEFrQ1ZDUmJLZTBR
            MFpqcEhKY1R5cHlLUU55TFdRSnFxLzQKFG5pd4GUKkr9fhznkKVWh5vV3xLi1C55
            o+7j9/ea/vRVx9mdFI8/L/qCF9s5p6mYfV0YYObfl5MOdqGn7o1Deg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-12T03:49:33Z"
    mac: ENC[AES256_GCM,data:ff9HoC9VosfwAjch4dyu41Y0KRf8kZMio9z9f+jdrjoFB5PR1JiVybYuGfy+GIt5CSTucSLdva7fz12c1JUz4H4Ev/LBj/KuhVuA7sNSKAeXZ2m890w+xXkmBlWZdkMNILxrMBwQ9IyOawjBaqLfCPmyAn+ETCAosNDknNbxfLM=,iv:GExLJjsnhtTGucupYGwypvZ5Z4okWqCeSKtEgfR+0Y4=,tag:Y9Y//o9PWmWdnvrRpISLGA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
